"use client";

import { useState } from "react";

import { useFirebaseUser } from "@/hooks/use-firebase-user";
import { useQuizAnalytics } from "@/hooks/use-quiz-analytics";

import QuizHistoryPanel from "./components/quiz-history-panel/quiz-history-panel.component";
import styles from "./page.module.css";
import Gallery from "./components/routes/gallery/gallery.component";
import App from "./components/routes/home/app.component";
import Projects from "./components/routes/projects/projects.component";
import AvatarDemo from "./components/routes/avatar/avatar.component";
import Report from "./components/routes/report/report.component";
import LogoTagSiteStarter from "./components/logo-tag-site-starter/logo-tag-site-starter";
import type { ViewKey } from "./components/routes/home/app.component";
import type { Segment } from "./components/content-segment/content-segment.component";

const CYBERSECURITY_TOPIC_OPTIONS = [
  "Phishing Awareness",
  "Ransomware Defense",
  "Identity and Access Management",
  "Network Security Monitoring",
  "Incident Response Fundamentals",
];

const platformLinks = [
  { label: "TryHackMe", href: "https://tryhackme.com/" },
  { label: "HackTheBox", href: "https://www.hackthebox.com/" },
  { label: "Hackviser", href: "https://hackviser.com/" },
  { label: "Hacknet", href: "https://store.steampowered.com/app/365450/Hacknet/" },
];

const teamContactHref =
  "mailto:kfrank1@my.tnstate.edu,jfinch10@my.tnstate.edu,jwebst20@my.tnstate.edu?subject=TSU%20SR%20Project%20Inquiry%202026&body=Hello%20TSU%20Cyber%20Edu%20team%2C%0D%0A%0D%0A";

const curatedByNclyne: Segment = {
  title: "Cyber True/False Challenge",
  subCopy: [
    "Choose a pre-vetted topic below to tailor your cybersecurity True/False questions.",
    "Answer each card with True or False. Difficulty increases each round.",
  ],
};

const spaceLooters: Segment = {
  title: "Cybersecurity-Focused T/F Questions - Generated by OpenAI",
  subCopy: [
    "Choose a Cyber Security topic to generate True/False questions.",
    "Answer each card with True or False. Difficulty increases each round.",
    "Watch your score and challenge yourself to improve with each attempt!",
  ],
  link: "",
};

export default function Home() {
  const [topic, setTopic] = useState(CYBERSECURITY_TOPIC_OPTIONS[0]);
  const [gallery, setGallery] = useState("rift-mark-2");
  const [currentView, setCurrentView] = useState<ViewKey>("home");
  const {
    userId,
    account,
    accountLabel,
    status: authStatus,
    errorMessage: authErrorMessage,
    isBusy: isAuthBusy,
    isEnabled,
    continueAsGuest,
    signInWithGoogle,
    signOutUser,
  } = useFirebaseUser();
  const {
    analytics,
    status: analyticsStatus,
    errorMessage: analyticsErrorMessage,
  } = useQuizAnalytics(userId);

  const homeButtons = [
    { buttonName: "Projects", action: "projects" as ViewKey, altname: "AI Generated Cybersecurity Questions" },
    { buttonName: "Gallery", action: "gallery" as ViewKey, altname: "OnCyber Gallery Scavenger Hunts" },
    { buttonName: "Avatar Demo", action: "avatar" as ViewKey, altname: "Avatar Cyber Walk Quiz" },
    { buttonName: "Report", action: "report" as ViewKey, altname: "AI Integrity Report" },
  ];

  const onTopicChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    setTopic(event.target.value);
  };

  const historyPanel = (
    <QuizHistoryPanel
      analytics={analytics}
      analyticsStatus={analyticsStatus}
      analyticsErrorMessage={analyticsErrorMessage}
      authStatus={authStatus}
      authErrorMessage={authErrorMessage}
      isFirebaseEnabled={isEnabled}
      userId={userId}
    />
  );

  const renderActiveView = () => {
    switch (currentView) {
      case "projects":
        return (
          <Projects
            spaceLooters={spaceLooters}
            curatedByNclyne={curatedByNclyne}
            topic={topic}
            topicOptions={CYBERSECURITY_TOPIC_OPTIONS}
            onTopicChange={onTopicChange}
            userId={userId}
            historyPanel={historyPanel}
          />
        );
      case "gallery":
        return <Gallery gallery={gallery} setGallery={setGallery} />;
      case "avatar":
        return (
          <AvatarDemo
            topicOptions={CYBERSECURITY_TOPIC_OPTIONS}
            userId={userId}
            historyPanel={historyPanel}
          />
        );
      case "report":
        return <Report userId={userId} />;
      default:
        return <App buttons={homeButtons} onNavigate={setCurrentView} />;
    }
  };

  return (
    <main className={styles.pageShell}>
      <LogoTagSiteStarter
        logoLabel="TSU Cyber Edu"
        tagline="Gamified Cybersecurity Platform | SR Project 2026"
        platformLinks={platformLinks}
        teamContactHref={teamContactHref}
        onNavigate={setCurrentView}
        auth={{
          accountKind: account.kind,
          accountLabel,
          authStatus,
          email: account.email,
          errorMessage: authErrorMessage,
          isBusy: isAuthBusy,
          isEnabled,
          photoURL: account.photoURL,
          continueAsGuest,
          signInWithGoogle,
          signOutUser,
        }}
      />
      <section className={styles.section}>{renderActiveView()}</section>
    </main>
  );
}
