"use client";

import { useEffect, useState } from "react";
import styles from "./page.module.css";
import Content from "./components/content/content.component";
import Gallery from "./components/routes/gallery/gallery.component";
import App from "./components/routes/home/app.component";
import Projects from "./components/routes/projects/projects.component";
import AvatarDemo from "./components/routes/avatar/avatar.component";
import LogoTagSiteStarter from "./components/logo-tag-site-starter/logo-tag-site-starter";
import type { ViewKey } from "./components/routes/home/app.component";
import type { Segment } from "./components/content-segment/content-segment.component";

const CYBERSECURITY_TOPIC_OPTIONS = [
  "Phishing Awareness",
  "Ransomware Defense",
  "Identity and Access Management",
  "Network Security Monitoring",
  "Incident Response Fundamentals",
];

const socials = [
  { platform: "game", link: "https://tryhackme.com/", text: "HackMe" },
  { platform: "game", link: "https://www.hackthebox.com/", text: "HackTheBox" },
  { platform: "game", link: "https://hackviser.com/", text: "HackViser" },
  { platform: "game", link: "https://store.steampowered.com/app/365450/Hacknet/", text: "Hacknet" },
  {
    platform: "mail",
    email: "kfrank1@my.tnstate.edu",
    name: "Kenny Frank",
    subject: "SR Project Inquiry 2025",
    text: "Contact - Kenny Frank",
  },
  {
    platform: "mail",
    email: "jfinch10@my.tnstate.edu",
    name: "Joshua Finch",
    subject: "SR Project Inquiry 2025",
    text: "Contact - Joshua Finch",
  },
  {
    platform: "mail",
    email: "jwebst20@my.tnstate.edu",
    name: "Jayden Webster",
    subject: "SR Project Inquiry 2025",
    text: "Contact - Jayden Webster",
  },
];

const curatedByNclyne: Segment = {
  title: "Cyber True/False Challenge",
  subCopy: [
    "Choose a pre-vetted topic below to tailor your cybersecurity True/False questions.",
    "Answer each card with True or False. Difficulty increases each round.",
  ],
};

const spaceLooters: Segment = {
  title: "Cybersecurity-Focused T/F Questions - Generated by OpenAI",
  subCopy: [
    "Choose a Cyber Security topic to generate True/False questions.",
    "Answer each card with True or False. Difficulty increases each round.",
    "Watch your score and challenge yourself to improve with each attempt!",
  ],
  link: "",
};

export default function Home() {
  const [topic, setTopic] = useState(CYBERSECURITY_TOPIC_OPTIONS[0]);
  const [videos, setVideos] = useState<unknown[]>([]);
  const [articles, setArticles] = useState<unknown[]>([]);
  const [gallery, setGallery] = useState("rift-mark-2");
  const [currentView, setCurrentView] = useState<ViewKey>("home");

  useEffect(() => {
    (async () => {
      try {
        const response = await fetch(
          "https://youtube.googleapis.com/youtube/v3/search?part=snippet&channelId=UCwZA4pIiYSJO9yrXOlcUMfQ&maxResults=3&order=date&key=AIzaSyDlI39i18q3VsuxcpwN4viDTitXUReCZkQ",
        );
        if (!response.ok) {
          console.error("YouTube fetch failed with status", response.status);
          setVideos([]);
          return;
        }
        const vids = await response.json();
        setVideos((vids && vids.items) || []);
      } catch (err) {
        console.error("Failed to fetch YouTube videos", err);
        setVideos([]);
      }
    })();
  }, []);

  useEffect(() => {
    (async () => {
      try {
        const response = await fetch("https://v1.nocodeapi.com/frnk/medium/WYojXOwHqYlmoYft");
        if (!response.ok) {
          console.error("Medium fetch failed with status", response.status);
          setArticles([]);
          return;
        }
        const items = await response.json();
        setArticles(items || []);
      } catch (err) {
        console.error("Failed to fetch Medium articles", err);
        setArticles([]);
      }
    })();
  }, []);

  const homeButtons = [
    { buttonName: "Projects", action: "projects" as ViewKey, altname: "AI Generated Cybersecurity Questions" },
    { buttonName: "Gallery", action: "gallery" as ViewKey, altname: "OnCyber Gallery Scavenger Hunts" },
    { buttonName: "Avatar Demo", action: "avatar" as ViewKey, altname: "Avatar Movement Demo" },
  ];

  const onTopicChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    setTopic(event.target.value);
  };

  const renderActiveView = () => {
    switch (currentView) {
      case "projects":
        return (
          <Projects
            spaceLooters={spaceLooters}
            curatedByNclyne={curatedByNclyne}
            topic={topic}
            topicOptions={CYBERSECURITY_TOPIC_OPTIONS}
            onTopicChange={onTopicChange}
          />
        );
      case "gallery":
        return <Gallery gallery={gallery} setGallery={setGallery} />;
      case "content":
        return <Content videos={videos} articles={articles} />;
      case "avatar":
        return <AvatarDemo />;
      default:
        return <App buttons={homeButtons} onNavigate={setCurrentView} />;
    }
  };

  return (
    <main className={styles.pageShell}>
      <LogoTagSiteStarter
        logoLabel="Gamified CyberSecurity Education Platform"
        tagline="TSU SR Project 2026"
        socials={socials}
        onNavigate={setCurrentView}
      />
      <section className={styles.section}>{renderActiveView()}</section>
    </main>
  );
}
